alias bat='batcat --plain'

alias eza.newest='eza --all --all --git --header --icons --group-directories-first --sort newest --long'
alias eza.size='eza --all --all --git --header --icons --group-directories-first --sort size --long'
alias eza.extension='eza --all --all --git --header --icons --group-directories-first --sort extension --long'
alias eza.dirs='eza --all --all --git --header --icons --only-dirs'

alias ls.eza='eza --all --all --git --header --icons --group-directories-first'
alias ls.eza.newest=eza.newest
alias ls.eza.size=eza.size
alias ls.eza.extension=eza.extension
alias ls.eza.dirs=eza.dirs
alias lsdirs=eza.dirs
