#!/usr/bin/env bash

## Config
WARN_SIZE_PCENT=80

## Need to disable python venv activate modificaion of the prompt.
export VIRTUAL_ENV_DISABLE_PROMPT=yes

# Change default behavior
#export PROMPT_PLUGINS_ENABLED=no
#export PROMPT_PLUGINS_COLOR_ENABLED=no
#export PROMPT_WARNING_SIZE_ENABLED=no
#export PROMPT_ICONS_ENABLED=no

## Color code for 'tput'
#RED=9
RED=196
ORANGE=202
BLUE=39
BROWN=137
GREEN=70
WHITE=231
DEFAULT=256

CONTEXT_BAR_BG_COLOR=236

#CLOCK_BEGIN_BG_COLOR=$DEFAULT
CLOCK_BEGIN_BG_COLOR=$CONTEXT_BAR_BG_COLOR
CLOCK_FG_COLOR=60
CLOCK_BG_COLOR=$CONTEXT_BAR_BG_COLOR
CLOCK_END_BG_COLOR=$CONTEXT_BAR_BG_COLOR

##  Decorator list:
## - none
## - bubble
## - pointer_in
## - pointer_out
## - arrow_right
## - arrow_left
## - parallelogram_right
## - parallelogram_left
## - circle_right
## - circle_left

VENV_DECORATOR=bubble

GIT_BG_COLOR=$CONTEXT_BAR_BG_COLOR
GIT_FG_COLOR=$WHITE
ICON_GIT_COLOR=$BROWN
ICON_GITHUB_COLOR=$BLUE
ICON_GITLAB_COLOR=$ORANGE

PYTHON_BEGIN_FG_COLOR=$CONTEXT_BAR_BG_COLOR
PYTHON_BG_COLOR=24
PYTHON_FG_COLOR=$WHITE
PYTHON_END_BG_COLOR=$CONTEXT_BAR_BG_COLOR

# To avoid counting some char (and tput) in de prompt 
BASH_ESCAPE_SPACE_BEGIN="\["
BASH_ESCAPE_SPACE_END="\]"

## Functions
disable_prompt_icons() {
  export PROMPT_ICONS_ENABLED=no
}

disable_prompt_plugins() {
  export PROMPT_PLUGINS_ENABLED=no
}

disable_prompt_plugins_color() {
  export PROMPT_PLUGINS_COLOR_ENABLED=no
}

disable_prompt_warning_size() {
  export PROMPT_WARNING_SIZE_ENABLED=no
}

enable_prompt_icons() {
  export PROMPT_ICONS_ENABLED=yes
}

enable_prompt_plugins() {
  export PROMPT_PLUGINS_ENABLED=yes
}

enable_prompt_plugins_color() {
  export PROMPT_PLUGINS_COLOR_ENABLED=yes
}

enable_prompt_warning_size() {
  export PROMPT_WARNING_SIZE_ENABLED=yes
}

is_prompt_icons_disabled() {
  return $([ "x$PROMPT_ICONS_ENABLED" = "xno" ])
}

is_prompt_prompt_plugins_disabled() {
  return $([ "x$PROMPT_PLUGINS_ENABLED" = "xno" ])
}

is_prompt_prompt_plugins_color_disabled() {
  return $([ "x$PROMPT_PLUGINS_COLOR_ENABLED" = "xno" ])
}

is_prompt_warning_size_disabled() {
  return $([ "x$PROMPT_WARNING_SIZE_ENABLED" = "xno" ])
}

is_not_ps1_colored() {
  echo $PS1 | grep -q 033
  [ $? -ne 0 ] && return
  return 1
}

# `man terminfo` other 'tput' options..

# We need to wrap 'tput in [ ] to tells Bash that code are to be considered zero-width.
# This avoid command line behavior issue cause be PS1 prompt
# As PS1 eval already pass we need to tell bash to interpret your barcket.
# We do that with a var opperator @P that expanding the value for prompting
tput_safe_zero_width() {
  echo "${BASH_ESCAPE_SPACE_BEGIN@P}$( tput $@ )${BASH_ESCAPE_SPACE_END@P}"
}

font_color() {
  is_not_ps1_colored && return 
  is_prompt_prompt_plugins_color_disabled && return 
  COLOR_CODE=$1
  tput_safe_zero_width setaf $COLOR_CODE
}

font_background_color() {
  is_not_ps1_colored && return 
  is_prompt_prompt_plugins_color_disabled && return 
  COLOR_CODE=$1
  tput_safe_zero_width setab $COLOR_CODE
}

font_warning() {
  font_color $RED
  tput_safe_zero_width bold
}

font_reset() {
  #tput sgr0
  tput_safe_zero_width sgr0
}

tput_rainbow() {
  for B in {1..256}; do
    echo -e "\nBackground $B , Foregrounds:"
    for F in {1..256}; do
      printf "$(tput setaf $F)$(tput setab $B) %-5s $(tput sgr0)" $F
    done
  done
}

prompt_message_wrapped_in() {
  decorator=${1:-bubble}
  fg_color=${2:-256}
  bg_color=${3:-77}
  message=${4:-}
  begin_bg_color=${5:-256}
  end_bg_color=${6:-256}


  case $decorator in
  pointer_in)
    icon_begin="left_hard_divider_inversed"
    icon_end="right_hard_divider_inversed"
    ;;
  pointer_out)
    icon_begin="right_hard_divider"
    icon_end="left_hard_divider"
    ;;
  arrow_right)
    icon_begin="left_hard_divider_inversed"
    icon_end="left_hard_divider"
    ;;
  arrow_left)
    icon_begin="right_hard_divider"
    icon_end="right_hard_divider_inversed"
    ;;
  parallelogram_right)
    icon_begin="lower_right_triangle"
    icon_end="upper_left_triangle"
    ;;
  parallelogram_left)
    icon_begin="upper_right_triangle"
    icon_end="lower_left_triangle"
    ;;
  circle_right)
    icon_begin="full_block"
    icon_end="right_half_circle"
    ;;
  circle_left)
    icon_begin="left_half_circle"
    icon_end="full_block"
    ;;
  bubble)
    icon_begin="left_half_circle"
    icon_end="right_half_circle"
    ;;
  *) # All or none
     icon_begin=''
     icon_end=''
     begin_border_color=''
     end_border_color=''
     ;;
  esac

  font_border_color="$(font_reset)$(font_color $bg_color)"

  [ -z $icon_begin ] || {
    begin_border_color="${font_border_color}$(font_background_color $begin_bg_color)"
    echo -e "${begin_border_color}$(font_icon $icon_begin)\c"
  }

  echo -e "$(font_color $fg_color)$(font_background_color $bg_color)${message}\c"

  [ -z $icon_end ] || {
    end_border_color="${font_border_color}$(font_background_color $end_bg_color)"
    echo -e "${end_border_color}$(font_icon $icon_end)\c"
  }

    echo -e "$(font_reset)\c"
}

tput_rainbow_background_for_font_color() {
  fg_color=${1:-231} # Default white
  nb_of_message_per_line=3
  count_message=0
  for BACK in {1..256} ; do
    ((count_message++))
    border_color="$(font_reset)$(font_color $BACK)$(font_background_color $DEFAULT)" 
    echo -e "${border_color}$(font_color $fg_color)$(font_background_color $BACK)   font $fg_color - background $BACK ${border_color}$(font_reset)   \c"
    [ $count_message -eq $nb_of_message_per_line ] && count_message=0 && echo -e "\n"
  done
  echo
}


prompt_warning_size() {
  is_prompt_warning_size_disabled  && return
  WARN_SIZE_PCENT=${WARN_SIZE_PCENT:-80}
  size_pcent_used=$(df --output=pcent . | tail -1 | tr -d '[:space:]%')
  [ $size_pcent_used -lt $WARN_SIZE_PCENT ] && return # Size is OK
  size_available=$(df -h --output=avail . | tail -1 | tr -d '[:space:]')
  this_filesystem=$(df --output=target . | tail -1 | tr -d '[:space:]')
  message="$(font_icon warning WARNING) Filesystem ${this_filesystem} ${size_available} free"
  prompt_message_wrapped_in "bubble" $DEFAULT $RED "$message"
}

font_icon() {
  icon=$1
  [ -n $2 ] && placeholder=$2 || placeholder=$icon
  is_prompt_icons_disabled && echo -n $placeholder || {

   ## Font icons (Need Nerd Font to rended in your terminal)
    case $icon in
    search)
      echo -n 
      ;;
    lock)
      echo -n 
      ;;
    cpu)
      echo -n 
      ;;
    network)
      echo -n 
      ;;
    code)
      echo -n 
      ;;
    studies)
      echo -n 
      ;;
    git)
      echo -n 
      ;;
    github)
      echo -n 
      ;;
    gitlab)
      echo -n 
      ;;
    branch)
      echo -n 
      ;;
    home)
      echo -n 
      ;;
    config)
      echo -n 
      ;;
    database)
      echo -n 
      ;;
    log)
      echo -n 󱂅
      ;;
    folder)
      echo -n 
      ;;
    open_folder)
      echo -n 
      ;;
    python)
      echo -n 
      ;;
    dialog)
      echo -n 
      ;;
    warning)
      echo -n 
      ;;
    clock)
      echo -n 󰅐
      ;;
    full_block)
      echo -n █
      ;;
    left_half_circle)
      echo -n 
      ;;
    right_half_circle)
      echo -n 
      ;;
    lower_left_triangle)
      echo -n 
      ;;
    lower_right_triangle)
      echo -n 
      ;;
    upper_left_triangle)
      echo -n 
      ;;
    upper_right_triangle)
      echo -n 
      ;;
    left_soft_divider)
      echo -n 
      ;;
    right_soft_divider)
      echo -n 
      ;;
    left_hard_divider)
      echo -n 
      ;;
    right_hard_divider)
      echo -n 
      ;;
    left_hard_divider_inversed)
      echo -n 
      ;;
    right_hard_divider_inversed)
      echo -n 
      ;;
   esac
  }
}

prompt_final_spacer() {
  last_spacer_with_icon='  '
  is_prompt_prompt_plugins_color_disabled || echo -n "$(font_reset)"
  is_prompt_icons_disabled || echo -n "$last_spacer_with_icon"
}

prompt_git() {
  current_branch=$(git branch --show-current 2>/dev/null)
  [ -z "${current_branch}" ] && return 1 # Not in a git direcory

  this_background_color=$(font_background_color $GIT_BG_COLOR)
  this_font_color=$(font_color $GIT_FG_COLOR)

  this_icon='git'
  this_icon_color=$(font_color $ICON_GIT_COLOR)

  # git@github.com:odraghi/tools.git
  origin=$(git remote get-url origin 2>/dev/null)

  echo $origin | grep -q "github.com:" && {
    this_icon='github'
    this_icon_color=$(font_color $ICON_GITHUB_COLOR)
  }

  echo $origin | grep -q "gitlab" && {
    this_icon='gitlab'
    this_icon_color=$(font_color $ICON_GITLAB_COLOR)
  }
  this_placeholder=$this_icon
  echo -e "${this_background_color}\c"
  echo -e "${this_icon_color}$(font_icon $this_icon $this_placeholder)\c"
  echo -e "${this_background_color}${this_font_color}  $(font_icon 'branch' 'branch:') ${current_branch}$(font_reset)\c"
}

prompt_venv_ps1_remove() {
  [ -z $VIRTUAL_ENV_PROMPT ] && return
  # Remove venv name from the prompt (it was injected in PS1 by bin/activate)
  #echo
  echo -e "\r\c"
}

prompt_venv_info() {
  [ -z $VIRTUAL_ENV ] && return 1
  this_icon='python'
  this_placeholder='python:'
  this_decorator=${VENV_DECORATOR:-bubble}
  prompt_message_wrapped_in $this_decorator \
                            $PYTHON_FG_COLOR $PYTHON_BG_COLOR \
                            "$(font_icon $this_icon $this_placeholder ) $(basename $VIRTUAL_ENV)" \
                            $PYTHON_BEGIN_FG_COLOR $PYTHON_END_BG_COLOR
}

prompt_venv_decorator_bubble() {
  VENV_DECORATOR=bubble
}

prompt_venv_decorator_pointer_in() {
  VENV_DECORATOR=pointer_in
}

prompt_venv_decorator_pointer_out() {
  VENV_DECORATOR=pointer_out
}

prompt_venv_decorator_arrow_right() {
  VENV_DECORATOR=arrow_right
}

prompt_venv_decorator_arrow_left() {
  VENV_DECORATOR=arrow_left
}

prompt_venv_decorator_parallelogram_right() {
  VENV_DECORATOR=parallelogram_right
}

prompt_venv_decorator_parallelogram_left() {
  VENV_DECORATOR=parallelogram_left
}

prompt_venv_decorator_circle_right() {
  VENV_DECORATOR=circle_right
}

prompt_venv_decorator_circle_left() {
  VENV_DECORATOR=circle_left
}

prompt_directory_icon() {
  this_icon=$1
  # Notice that we call font_icon with only 1 arg. (no placeholder)
  echo "$(font_color $DEFAULT)$(font_icon $this_icon)$(prompt_final_spacer)"
}

prompt_directory() {
  echo "$PWD" | grep -q "^/etc"      && prompt_directory_icon config   && return
  echo "$PWD" | grep -qe "/logs\?\$" && prompt_directory_icon log      && return
  echo "$PWD" | grep -q "^/data"     && prompt_directory_icon database && return
  echo "$PWD" | grep -q "^${HOME}$"  && prompt_directory_icon home     && return
  prompt_directory_icon open_folder
}

prompt_clock() {
  prompt_time='\A'
  message="$(font_icon clock) ${prompt_time@P}"
  prompt_message_wrapped_in "none" \
                            $CLOCK_FG_COLOR $CLOCK_BG_COLOR \
                            "$message" \
                            $CLOCK_BEGIN_BG_COLOR $CLOCK_END_BG_COLOR
}

prompt_separator_context_bar() {
  prompt_message_wrapped_in "none" \
                            $CONTEXT_BAR_BG_COLOR $CONTEXT_BAR_BG_COLOR \
                            " " \
                            $CONTEXT_BAR_BG_COLOR $CONTEXT_BAR_BG_COLOR
}

prompt_begin_context_bar() {
  prompt_message_wrapped_in "bubble" \
                            $CONTEXT_BAR_BG_COLOR $CONTEXT_BAR_BG_COLOR \
                            "" \
                            $DEFAULT $CONTEXT_BAR_BG_COLOR
}

prompt_end_context_bar() {
  prompt_message_wrapped_in "bubble" \
                            $CONTEXT_BAR_BG_COLOR $CONTEXT_BAR_BG_COLOR \
                            "" \
                            $CONTEXT_BAR_BG_COLOR $DEFAULT
}

prompt_plugins() {
  is_prompt_prompt_plugins_disabled && return
  [ $TERM != 'xterm-256color' ] && disable_prompt_icons && disable_prompt_plugins_color
  prompt_venv_ps1_remove # Must be the first
  echo
  prompt_begin_context_bar
  prompt_clock
  prompt_separator_context_bar
  prompt_venv_info && prompt_separator_context_bar
  prompt_git
  #prompt_message_wrapped_in "bubble" $DEFAULT $RED "$(font_icon dialog) Hello la famille ca va chez vous ?"
  prompt_end_context_bar
  prompt_warning_size
  echo
  prompt_directory 
}

PS1="\$(prompt_plugins $?)${PS1}"
