#!/usr/bin/env bash

prompt_git() {
   current_branch=$(git branch --show-current 2>/dev/null)
   [ -z "${current_branch}" ] && return 1 # Not in a git direcory

   echo $PS1 | grep -q 033 && color_prompt=yes || color_prompt=no

   WHITE=256
   GREY=237
   YELLOW=202

   # `man terminfo`  to see tput option..
   TEXT_COLOR="$(tput setaf $WHITE)"
   ICON_GIT_COLOR="$(tput setaf $WHITE)"

   ICON_GITHUB= 
   ICON_GITLAB=
   ICON_GIT= 
   ICON_BRANCH=
   this_icon=$ICON_GIT

   origin=$(git remote get-url origin 2>/dev/null | sed "s/git@\(.*\)\.git/\1/")
   origin=${origin:-:local} # Init if previous command failed
   # git@github.com:odraghi/tools.git
   echo $origin | grep -q "^github.com" && this_icon=$ICON_GITHUB && ICON_GIT_COLOR="$(tput setaf $WHITE)"
   echo $origin | grep -q "^gitlab" && this_icon=$ICON_GITLAB && ICON_GIT_COLOR="$(tput setaf $YELLOW)"
   project=${origin#*:}

   [ ${color_prompt} = 'no' ] && ICON_GIT_COLOR='' && TEXT_COLOR=''
   echo "${ICON_GIT_COLOR}${this_icon}   ${TEXT_COLOR}${ICON_BRANCH} ${current_branch} "
}

prompt_plugins() {
  prompt_git
}
